<a href="https://colab.research.google.com/github/bigdatakang0000/START/blob/main/%EA%B3%BC%EB%AA%A9%EB%B3%84_%EA%B3%B5%EB%B6%84%EC%82%B0_%EA%B3%84%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import numpy as np
import pandas as pd
%precision 3
pd.set_option('precision',3)

In [61]:
df= pd.read_csv("/content/drive/MyDrive/파이썬 통계분석 책_파일/source (1)/python_stat_sample-master/data/ch2_scores_em.csv")

In [62]:
en_scores = np.array(df['english'])[:10]
ma_scores = np.array(df['mathematics'])[:10]
scores_df = pd.DataFrame({'english' : en_scores,
                          'mathematics' : ma_scores}, 
                         index= pd.Index(['A','B','C','D','E','F','G','H','I','J'],
                                         name='student'))
scores_df

         english  mathematics
student
A             42           65
B             69           80
C             56           63
D             41           63
E             57           76
F             48           60
G             65           81
H             49           66
I             65           78
J             58           82

In [63]:
summary_df= scores_df.copy()
summary_df['english_deviation']= \
    summary_df['english'] - summary_df['english']. mean()
summary_df['mathematics_deviation']= \
    summary_df['mathematics'] - summary_df['mathematics']. mean()
summary_df['product of deviation']= \
    summary_df['english_deviation'] * summary_df['mathematics_deviation']
summary_df

,english,mathematics,english_deviation,mathematics_deviation,product of deviation
student,,,,,
A,42,65,-13.0,-6.4,83.2
B,69,80,14.0,8.6,120.4
C,56,63,1.0,-8.4,-8.4
D,41,63,-14.0,-8.4,117.6
E,57,76,2.0,4.6,9.2
F,48,60,-7.0,-11.4,79.8
G,65,81,10.0,9.6,96.0
H,49,66,-6.0,-5.4,32.4
I,65,78,10.0,6.6,66.0
J,58,82,3.0,10.6,31.8

In [73]:
summary_df['product of deviations'].mean()

KeyError: ignored

In [71]:
fig = plt.figure(figsize=(10,8))
ax= fig.add_subplot(111)

c=ax.hist2d(english_scores, math_scores, bins=[9,8], range=[(35,80),(55,95)])
ax.set_xlabel('english')
ax.set_ylabel('mathmetics')
ax.set_xticks(c[1])
ax.set_yticks(c[2])

#컬러바 표시
fig.colorbar(c[3], ax=ax)
plt.show()

NameError: ignored